const state={all:[],view:[],category:"all",location:"all",experience:"all",freshness:"all",sort:"fresh",saved:new Set(JSON.parse(localStorage.getItem("radar-saved")||"[]")),savedOnly:false};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));
const age=x=>{const d=x.posted_at||x.date;if(!d)return 999;const n=(Date.now()-new Date(d).getTime())/86400000;return Number.isFinite(n)?Math.max(0,n):999};
const ageText=a=>a<=1?"Today":a<=3?Math.max(1,Math.floor(a))+"d ago":a<30?Math.floor(a)+"d ago":"Older";
function persist(){localStorage.setItem("radar-saved",JSON.stringify([...state.saved]));$("#savedCount").textContent=state.saved.size}
function matches(x){const q=$("#search").value.trim().toLowerCase();if(state.savedOnly&&!state.saved.has(x.url||x.title))return false;if(state.category!=="all"&&!(x.categories||[]).includes(state.category))return false;if(state.location!=="all"&&!(x.location_key||"").includes(state.location))return false;if(state.experience!=="all"&&x.experience!==state.experience)return false;if(state.freshness!=="all"&&age(x)>+state.freshness)return false;const hay=[x.title,x.company,x.location,(x.categories||[]).join(" "),x.source].join(" ").toLowerCase();if(q&&!hay.includes(q))return false;return true}
function card(x,featured,index){const id=x.url||x.title,saved=state.saved.has(id),a=age(x),pay=x.salary||x.stipend||"",cls=featured?"featured-job":"";let meta="";if(pay)meta+="<span>"+esc(pay)+"</span>";if(x.experience&&x.experience!=="unknown")meta+="<span>"+esc(x.experience)+"</span>";meta+='<span class="radar">RADAR '+esc(x.score||0)+"</span>";return '<article class="job '+cls+'" style="animation-delay:'+(Math.min(index||0,10)*35)+'ms"><div class="job-top"><span class="type">'+esc(x.type)+'</span><span class="age">'+esc(ageText(a))+'</span><button class="save '+(saved?"on":"")+'" data-save="'+esc(id)+'" aria-label="'+(saved?"Remove from saved":"Save opportunity")+'">'+(saved?"★":"☆")+'</button></div><div class="job-main"><div class="company-mark">'+esc((x.company||"?").slice(0,1).toUpperCase())+'</div><div class="job-copy"><h3>'+esc(x.title)+'</h3><p class="company">'+esc(x.company)+'</p><p class="place">'+esc(x.location||"India")+(x.mode?" · "+esc(x.mode):"")+'</p></div></div><div class="job-meta">'+meta+'</div><div class="job-bottom"><span class="reason">'+esc((x.reasons||[]).slice(0,2).join(" · ")||"Relevant opportunity")+'</span><a href="'+esc(x.url)+'" target="_blank" rel="noopener noreferrer">Open listing ↗</a></div></article>'}
function filtered(){let out=state.all.filter(matches);out.sort((a,b)=>state.sort==="score"?(b.score||0)-(a.score||0):age(a)-age(b));return out}
function updateActive(){const labels=[];if(state.category!=="all")labels.push(["category",state.category]);if(state.location!=="all")labels.push(["location",state.location]);if(state.experience!=="all")labels.push(["experience",state.experience]);if(state.freshness!=="all")labels.push(["freshness",state.freshness+"d"]);if(state.savedOnly)labels.push(["saved","Saved"]);$("#activeFilters").innerHTML=labels.map(x=>'<button data-remove="'+x[0]+'">'+esc(x[1])+" ×</button>").join("");$$("[data-remove]").forEach(b=>b.onclick=()=>{const k=b.dataset.remove;if(k==="saved")state.savedOnly=false;else state[k]="all";syncControls();render()})}
function render(){const out=filtered();state.view=out;$("#resultCount").textContent=out.length;$("#feed").innerHTML=out.slice(3).map((x,i)=>card(x,false,i)).join("");$("#featured").innerHTML=out.length?'<div class="featured-label"><span>RADAR PICKS</span><small>Highest-signal opportunities in your current view</small></div>'+out.slice(0,3).map((x,i)=>card(x,true,i)).join(""):"";$("#empty").hidden=out.length>0;updateActive();bindSave();$("#feedStatus").textContent=state.savedOnly?"● saved view":"● live";$("#heroCount").textContent=state.all.length||"0";$("#heroFresh").textContent=state.all.length?ageText(Math.min(...state.all.map(age))):"—";$("#heroSources").textContent=new Set(state.all.map(x=>x.source).filter(Boolean)).size||"—"}
function bindSave(){$$(".save").forEach(b=>b.onclick=()=>{const id=b.dataset.save;state.saved.has(id)?state.saved.delete(id):state.saved.add(id);persist();render()})}
function syncControls(){$$("[data-cat]").forEach(b=>b.classList.toggle("selected",b.dataset.cat===state.category));$("#location").value=state.location;$("#experience").value=state.experience;$("#freshness").value=state.freshness;$("#sort").value=state.sort}
function clear(){state.category=state.location=state.experience=state.freshness="all";state.sort="fresh";state.savedOnly=false;$("#search").value="";syncControls();render()}
function reveal(){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("visible")}),{threshold:.08});$$(".reveal").forEach(e=>io.observe(e))}
function surprise(){if(!state.all.length)return;const pool=state.all.filter(x=>age(x)<=7);const x=pool[Math.floor(Math.random()*(pool.length||1))]||state.all[0];window.open(x.url,"_blank","noopener,noreferrer")}
fetch("data/opportunities.json",{cache:"no-store"}).then(r=>{if(!r.ok)throw new Error("feed");return r.json()}).then(d=>{state.all=Array.isArray(d)?d:[];const dates=state.all.map(x=>x.posted_at||x.date).filter(Boolean).sort().reverse();$("#updated").textContent=dates[0]?"Updated "+new Date(dates[0]).toLocaleDateString("en-IN",{day:"numeric",month:"short"}):"Feed active";$("#boot").classList.add("done");persist();render();reveal()}).catch(()=>{$("#boot").classList.add("done");$("#updated").textContent="Feed unavailable";$("#feedStatus").textContent="● offline";$("#featured").innerHTML="";$("#empty").hidden=false;render();reveal()});
$$("[data-cat]").forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;state.savedOnly=false;render()});
$("#location").onchange=e=>{state.location=e.target.value;state.savedOnly=false;render()};$("#experience").onchange=e=>{state.experience=e.target.value;state.savedOnly=false;render()};$("#freshness").onchange=e=>{state.freshness=e.target.value;state.savedOnly=false;render()};$("#sort").onchange=e=>{state.sort=e.target.value;render()};$("#search").oninput=render;
$("#clearFilters").onclick=clear;$("#emptyReset").onclick=clear;$("#savedBtn").onclick=()=>{state.savedOnly=!state.savedOnly;render()};$("#surprise").onclick=surprise;
document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();$("#search").focus()}if(e.key==="Escape"&&document.activeElement===$("#search")){$("#search").value="";render()}});
persist();